# Generated by Django 5.2.8 on 2025-12-16 03:05

import django.db.models.deletion
import users.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.IntegerField(verbose_name=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.application'))),
                ('approved', models.IntegerField()),
                ('action', models.CharField(max_length=255)),
                ('application_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('login', models.CharField(max_length=255, unique=True, verbose_name='login')),
                ('password', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('reject', 'Reject'), ('pending', 'Pending')], default='pending', max_length=15)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('INN', models.BigIntegerField()),
                ('OGRN', models.BigIntegerField()),
                ('name_company', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('reject', 'Reject'), ('pending', 'Pending'), ('freeze', 'Freeze')], default='pending', max_length=15)),
                ('founder', models.ManyToManyField(related_name='founder', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_contract', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('reject', 'Reject'), ('pending', 'Pending')], default='pending', max_length=16)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='users.companies')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_request', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('application_created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_owner', to=settings.AUTH_USER_MODEL)),
                ('for_company', models.ManyToManyField(related_name='application_for_company', to='users.companies')),
                ('for_contract', models.ManyToManyField(related_name='application_for_contract', to='users.contracts')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=users.models.token_expired_at)),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ammount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_transaction', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('sender_agreement', models.UUIDField(null=True)),
                ('recipient_agreement', models.UUIDField(null=True)),
                ('data_trasaction', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.contracts')),
            ],
        ),
    ]
